### ISSUE TITLE
unit test TestAllSourcesWithFileOutput is unstable

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/cmd-exclude-prefixes-k8s#180]
## Build
https://github.com/networkservicemesh/cmd-exclude-prefixes-k8s/actions/runs/3176966860/jobs/5176870045

**Comment by denis-tingaikin** [comment]
The problem is still actual https://github.com/networkservicemesh/cmd-exclude-prefixes-k8s/actions/runs/6430072106/attempts/1

**Comment by NikitaSkrynnik** [comment]
Fixed here https://github.com/networkservicemesh/cmd-exclude-prefixes-k8s/pull/250

**Comment by denis-tingaikin** [comment]
Seems like done
