### ISSUE TITLE
cmd-exclude-prefixes-k8s out of date

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/cmd-exclude-prefixes-k8s#45]
[Pushes from sdk-k8s](https://github.com/networkservicemesh/sdk-k8s/actions/runs/821633437) are failing due to cmd-exclude-prefixes-k8s needing to be updated.

**Comment by denis-tingaikin** [comment]
@edwarnicke Can you share your thoughts about priorities for test and update cmd-exclude-prefixes-k8s?
